import type { Recipe } from "@/lib/types";

export const mediterraneanPrawnPasta: Recipe = {
  slug: "mediterranean-prawn-pasta",
  title: "Mediterranean Prawn Pasta",
  subtitle: "Garlic, chilli, cherry tomatoes, white wine, lemon, parsley",
  tagline: "Twenty-minute linguine tossed through sautéed prawns in a bright, garlicky tomato-white wine sauce. The kind of dinner that turns a Tuesday into something worth lingering over.",
  hero: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=1600&q=80",
  heroAlt: "Linguine pasta tossed with prawns in a garlic and cherry tomato sauce",
  cuisine: "Mediterranean",
  category: "pasta",
  methods: ["stovetop"],
  methodOptions: [
    { method: "stovetop", label: "Stovetop", time: "20–25 min", temp: "medium-high", note: "Fast, fresh, one pan" },
  ],
  equipment: ["skillet", "pot", "knife", "scale"],
  dietTags: ["high-protein", "mediterranean", "pescatarian"],
  difficulty: "intermediate",
  servings: { base: 1, min: 1, max: 4 },
  timeMin: { active: 20, passive: 5 },
  ingredients: [
    { id: "pasta", name: "Linguine or spaghetti", everyday: "1 handful", qty: 100, unit: "g", gram: 100, group: "pantry" },
    { id: "prawns", name: "Raw prawns, peeled", everyday: "1 large handful", qty: 150, unit: "g", gram: 150, group: "protein", localProduct: "Woolworths raw prawns" },
    { id: "garlic", name: "Garlic, finely chopped", everyday: "3 cloves", qty: 3, unit: "clove", gram: 12, group: "aromatic" },
    { id: "chilli", name: "Dried chilli flakes", everyday: "a pinch", qty: 0.5, unit: "tsp", gram: 1, group: "seasoning", scaling: { kind: "tapered", category: "spice" } },
    { id: "tomatoes", name: "Cherry tomatoes, halved", everyday: "1 cup", qty: 150, unit: "g", gram: 150, group: "produce" },
    { id: "wine", name: "Dry white wine", everyday: "a splash", qty: 60, unit: "ml", gram: 55, group: "pantry" },
    { id: "lemon", name: "Lemon (juice)", everyday: "½ a lemon", qty: 0.5, unit: "piece", gram: 25, group: "finish" },
    { id: "parsley", name: "Fresh parsley, chopped", everyday: "a small handful", qty: 1, unit: "handful", gram: 5, group: "finish" },
    { id: "oil", name: "Olive oil", everyday: "a glug", qty: 2, unit: "tbsp", gram: 30, group: "fat" },
    { id: "salt", name: "Sea salt & black pepper", everyday: "to taste", gram: null, group: "seasoning", scaling: { kind: "tapered", category: "salt" } },
    { id: "spring-onion", name: "Spring onion, sliced", everyday: "1 spring onion", qty: 1, unit: "piece", gram: 15, group: "aromatic", optional: true },
  ],
  steps: [
    { id: "s1", instruction: "Prep everything first — halve the tomatoes, chop the garlic, slice the spring onion, and squeeze the lemon.", method: "prep", calloutIds: ["mise-en-place"] },
    { id: "s2", instruction: "Boil the pasta in salted water until al dente, then scoop out a mug of cooking water before draining.", method: "stovetop", durationMin: 10, calloutIds: ["salt-pasta-water", "dont-rinse-pasta"] },
    { id: "s3", instruction: "Heat the oil in a skillet over medium-high heat, add the prawns in a single layer and sear for 1–2 minutes each side until pink and golden.", method: "stovetop", durationMin: 3, calloutIds: ["preheat-pan", "dont-crowd-pan"] },
    { id: "s4", instruction: "Push the prawns aside, add the garlic and chilli flakes, and fry for 30 seconds until fragrant but not browned.", method: "stovetop", calloutIds: ["garlic-late"] },
    { id: "s5", instruction: "Toss in the cherry tomatoes and splash in the white wine — let it bubble for 3–4 minutes until the tomatoes soften and the sauce reduces slightly.", method: "stovetop", durationMin: 4 },
    { id: "s6", instruction: "Add the drained pasta to the pan, toss with the sauce, and loosen with the reserved pasta water until glossy and emulsified.", method: "stovetop", calloutIds: ["deglaze-fond"] },
    { id: "s7", instruction: "Off the heat: return the prawns to the pan, squeeze over the lemon juice, scatter with parsley and spring onion, then toss and serve.", method: "prep", calloutIds: ["acid-balances", "delicate-herbs-late"] },
  ],
  nutrition: { energyKJ: 2180, energyKcal: 520, protein_g: 32, carbs_g: 68, fat_g: 18, fibre_g: 4, sugar_g: 8, sodium_mg: 480 },
  pairings: [
    { type: "wine", name: "Sauvignon Blanc", detail: "Crisp, grassy acidity cuts through the garlic and oil.", kJ: 520, localPick: "Durbanville Hills Sauvignon Blanc" },
    { type: "wine", name: "Chenin Blanc", detail: "Off-dry, stone fruit notes complement the sweetness of prawns.", kJ: 480, localPick: "Kleine Zalze Vineyard Selection Chenin Blanc" },
    { type: "mocktail", name: "Lemon-Rosemary Spritz", detail: "Zero-proof, aromatic, mirrors the dish's flavours.", kJ: 60 },
  ],
  sides: [
    { name: "Garlic bread", kJ: 720, match: 94 },
    { name: "Green salad with balsamic", kJ: 180, match: 89 },
    { name: "Roast baby potatoes", kJ: 560, match: 78 },
    { name: "Grilled asparagus", kJ: 140, match: 82 },
  ],
};
