import type { Recipe } from "@/lib/types";

export const spaghettiBolognaise: Recipe = {
  slug: "spaghetti-bolognaise",
  title: "Spaghetti Bolognaise",
  subtitle: "Proper ragù, bachelor timing",
  tagline: "A proper one-portion beef ragù — soffritto, beef mince, tomato, and a splash of milk and wine, simmered while the pasta boils. Finished with parmesan. The real deal, scaled for one.",
  hero: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=1600&q=80",
  heroAlt: "Spaghetti bolognaise with rich beef ragù sauce and parmesan",
  cuisine: "Italian",
  category: "pasta",
  methods: ["stovetop", "oven"],
  methodOptions: [
    { method: "stovetop", label: "Stovetop", time: "35–40 min", temp: "med-low", note: "Best control, faster" },
    { method: "oven", label: "Oven", time: "2 hrs", temp: "160 °C", note: "Deep flavour, hands-off" },
  ],
  equipment: ["skillet", "pot", "knife", "scale"],
  dietTags: ["high-protein"],
  difficulty: "intermediate",
  servings: { base: 1, min: 1, max: 4 },
  timeMin: { active: 25, passive: 15 },
  ingredients: [
    { id: "spaghetti", name: "Spaghetti", everyday: "100 g dried spaghetti", qty: 100, unit: "g", gram: 100, group: "pantry" },
    { id: "beef", name: "Beef mince", everyday: "120 g beef mince", qty: 120, unit: "g", gram: 120, group: "protein", substitutes: [{ name: "Beef-pork mix", note: "Half beef, half pork for extra richness" }] },
    { id: "onion", name: "Onion, finely diced", everyday: "½ a medium onion", qty: 0.5, unit: "piece", gram: 40, group: "aromatic", prep: "finely diced" },
    { id: "carrot", name: "Carrot, finely diced", everyday: "½ a medium carrot", qty: 0.5, unit: "piece", gram: 30, group: "produce", prep: "finely diced" },
    { id: "celery", name: "Celery, finely diced", everyday: "1 small stalk", qty: 1, unit: "stalk", gram: 15, group: "produce", prep: "finely diced" },
    { id: "garlic", name: "Garlic, minced", everyday: "2 cloves", qty: 2, unit: "clove", gram: 8, group: "aromatic" },
    { id: "oil", name: "Olive oil", everyday: "a glug", qty: 1, unit: "tbsp", gram: 15, group: "fat" },
    { id: "tomato", name: "Chopped tomatoes", everyday: "½ x 400 g tin chopped tomatoes", qty: 200, unit: "g", gram: 200, group: "pantry", localProduct: "KOO chopped tomatoes" },
    { id: "passata", name: "Tomato passata", everyday: "100 ml passata", qty: 100, unit: "ml", gram: 100, group: "pantry" },
    { id: "milk", name: "Milk", everyday: "2 tbsp milk", qty: 2, unit: "tbsp", gram: 30, group: "dairy" },
    { id: "wine", name: "Red wine", everyday: "a splash of red wine", qty: 30, unit: "ml", gram: 24, group: "pantry", optional: true },
    { id: "salt", name: "Sea salt", everyday: "salt", gram: null, scaling: { kind: "tapered", category: "salt" }, group: "seasoning" },
    { id: "pepper", name: "Black pepper", everyday: "black pepper", gram: null, scaling: { kind: "tapered", category: "spice" }, group: "seasoning" },
    { id: "parmesan", name: "Parmesan, grated", everyday: "a handful of parmesan", qty: 20, unit: "g", gram: 20, group: "finish", localProduct: "Woolworths Parmesan" },
  ],
  steps: [
    { id: "s1", instruction: "Prep the soffritto: finely dice onion, carrot, and celery. Mince the garlic. Measure everything else.", method: "prep", calloutIds: ["mise-en-place"] },
    { id: "s2", instruction: "Heat oil in a skillet over medium heat. Add the soffritto vegetables with a pinch of salt and cook 8–10 minutes until soft and starting to caramelise.", method: "stovetop", durationMin: 10, calloutIds: ["salt-in-layers", "baking-soda-onions"] },
    { id: "s3", instruction: "Add the garlic and cook for 1 minute until fragrant, then add the beef mince. Break it up and brown for 5–6 minutes.", method: "stovetop", durationMin: 6, calloutIds: ["garlic-late"] },
    { id: "s4", instruction: "Pour in the wine (if using) and let it bubble for 1 minute, then add the milk and simmer until absorbed.", method: "stovetop", durationMin: 2 },
    { id: "s5", instruction: "Stir in the chopped tomatoes and passata. Season with salt and pepper, then reduce heat to low and simmer for 15–20 minutes while you boil the pasta.", method: "stovetop", durationMin: 20, calloutIds: ["salt-in-layers", "acid-balances"] },
    { id: "s6", instruction: "Boil spaghetti in heavily salted water until al dente, then drain — don't rinse.", method: "stovetop", durationMin: 10, calloutIds: ["salt-pasta-water", "dont-rinse-pasta"] },
    { id: "s7", instruction: "Toss the pasta with the sauce, pile into a bowl, and finish with a generous handful of parmesan.", method: "prep", calloutIds: ["acid-balances"] },
  ],
  nutrition: { energyKJ: 2890, energyKcal: 690, protein_g: 42, carbs_g: 82, fat_g: 22, fibre_g: 6, sugar_g: 12, sodium_mg: 710 },
  pairings: [
    { type: "wine", name: "Shiraz", detail: "Bold and fruity — stands up to the rich beef and tomato.", kJ: 560, localPick: "Two Oceans Shiraz" },
    { type: "mocktail", name: "Tomato-Basil Spritz", detail: "Zero-proof tomato water with basil and lime.", kJ: 60 },
  ],
  sides: [
    { name: "Garlic bread", kJ: 920, match: 94 },
    { name: "Green salad", kJ: 180, match: 89 },
    { name: "Roast baby potatoes", kJ: 760, match: 82 },
    { name: "Steamed green beans", kJ: 140, match: 78 },
  ],
  sources: [
    { name: "Serious Eats — The Food Lab: Bolognaise", url: "https://www.seriouseats.com/the-food-lab-complete-guide-to-bolognese-sauce" },
    { name: "Massimo Bottura — Traditional Ragù", url: "https://www.massimobottura.it/recipes/traditional-ragu" },
  ],
};
